return {
  version = 3,
  map = {
    -- Basic info
    name = "Tango Uniform Romeo Delta",
    description = "12x12 map with 6 players, snaking valley, geos, and central metal corridor",
    author = "Generated by Krazer",
    -- Map size in BAR units
    width = 4097,
    height = 4097,
    gravity = 120,
    tidal = 0,

    -- Metal map reference
    metalMap = "metal_valley_path.png",

    -- Start positions (x, z coordinates, y computed from heightmap)
    -- Top-left corner cluster
    startPos = {
      {x=500, z=500},
      {x=650, z=500},
      {x=800, z=900},

      -- Bottom-right corner cluster
      {x=3597, z=3597},
      {x=3747, z=3597},
      {x=3847, z=3297},
    },

    -- Geothermal vents (raised)
    geoSpots = {
      {x=3297, z=200},   -- Top-right geo
      {x=200, z=3297},   -- Bottom-left geo
    },

    -- Optional map features
    features = {
      -- Can add trees, rocks, wrecks later
    },

    -- Optional game options
    options = {
      allowUnits = true,
      fogOfWar = true,
    },
  }
}
